### ISSUE TITLE
How should roles be added to the project?

### ISSUE THREAD

**Issue by flyemsafe** [RedHatSatellite/satellite-ansible-compilation#4]
I am in favor of adding roles to the project using Git  submodule.

e.g.

```
git submodule add https://github.com/flyemsafe/redhat-satellite-quickstart.git redhat-satellite-quickstart
```

This makes to me to because most of these roles will have their own lifecycle and this project is essentially just a repository of roles based on FAM. Can we move to adopt this as the way to add roles to this project?

**Comment by sthirugn** [comment]
I am ok to just add the roles as subfolders in this repo instead of git submodules.  Let's see if others have any other opinions.

**Comment by sthirugn** [comment]
@ehelms @evgeni thoughts?

**Comment by evgeni** [comment]
I'd prefer this repo being the real repo the role lives in, and you get commit rights over submodules.

But I have no (official) say here ;)

**Comment by ehelms** [comment]
I lean towards what @evgeni said. I recall our intent was to make this a central repository of roles to inspire collaboration and knowledge sharing with an eye towards generalizing and promotion to foreman-ansible-modules. Git submodules will require users to go track down each individual role rather than centralized contribution. All maintainers should get access rights to this repository to allow iterating on their roles. And we will work to reduce any friction.

**Comment by sthirugn** [comment]
@flyemsafe looks like there are more votes to keep this a real repo vs. git submodules. Can you please update the PR when you get a chance? Thanks!

**Comment by flyemsafe** [comment]
> I lean towards what @evgeni said. I recall our intent was to make this a central repository of roles to inspire collaboration and knowledge sharing with an eye towards generalizing and promotion to foreman-ansible-modules. Git submodules will require users to go track down each individual role rather than centralized contribution. All maintainers should get access rights to this repository to allow iterating on their roles. And we will work to reduce any friction.

The problem i have with this approach is that the role now becomes part of this repo's life cycle. If I am only interested in consuming a role from this repo I have to consume all. I often include a requirements.yml with my ansible projects, when using this with Tower the roles are downloaded automatically. e.g.

```
$ cat playbooks/requirements.yml
- src: https://github.com/flyemsafe/redhat-satellite-quickstart.git
  version: master
```
How would I continue to do this following the *real repo* method?

**Comment by sthirugn** [comment]
> ```
> $ cat playbooks/requirements.yml
> - src: https://github.com/flyemsafe/redhat-satellite-quickstart.git
>   version: master
> ```
> 
> How would I continue to do this following the _real repo_ method?
@flyemsafe can this help? https://github.com/ansible/ansible/issues/16804#issue-167166781

**Comment by ehelms** [comment]
Our original goal was to collect roles in a single place for users to use. I'm not seeing the downside of a user installing multiple roles as they aren't required to use those roles. The git submodule route feels more like going the route of providing a centralized place to point users *at* roles. In which case, we could just have a README with links out to those roles.

Thoughts?

**Comment by sthirugn** [comment]
> Our original goal was to collect roles in a single place for users to use. I'm not seeing the downside of a user installing multiple roles as they aren't required to use those roles. The git submodule route feels more like going the route of providing a centralized place to point users _at_ roles. In which case, we could just have a README with links out to those roles.
> 

Just having a README is fine for me to start with. We can see how things go and change it if required.
The challenge will be to make sure the roles listed in README are accurate and up-to-date, but it should be the end user's responsibility probably.
Let me know if others are okay with this approach, so we can start moving forward.

**Comment by sthirugn** [comment]
@flyemsafe Are you okay with my previous comment? I will perhaps go ahead and do this change tomorrow if that's okay.

**Comment by sthirugn** [comment]
I added a new `Roles.md` to capture the Roles information. See https://github.com/RedHatSatellite/satellite-ansible-roles/pull/8

**Comment by sthirugn** [comment]
The PR is merged, closing this issue.
