### ISSUE TITLE
Rule Loosening (Atleast Initially)

### ISSUE THREAD

**Issue by jjaswanson4** [RedHatSatellite/satellite-ansible-compilation#7]
> "The roles shall not use hammer via command/shell or the uri module to talk to the API directly."
> "The roles should not duplicate functionality of other existing roles in the same repository."

I don't disagree with this in theory, but I'm not sure we can put a hard ban on these this early. Since the modules aren't GA (and don't cover all functionality, like adding capsules, running the satellite installer, etc) I think we have to allow this as long as there is intention/work to re-code with the modules. "Technically speaking", we do fully support hammer and using the API so supportability isn't affected by leveraging them.

Thoughts?

**Comment by sthirugn** [comment]
If there is a genuine reason for using the methods described in the quoted text, then I think it should be allowed.

**Comment by aoyawale** [comment]
I think like we discussed during our meeting that for those cases using those modules is fine as we are starting out. Since those modules are not ready or not there yet.

**Comment by bherrin3** [comment]
The `README.md` has been updated to allow this to be more of a compilation and non-official source for information. Also, the originally quoted text is no longer present.

Closing, as I believe the intent of this `compilation` will be more open, as long as bare-minimum requirements and linting are met.
